### ISSUE TITLE
blogfeed

### ISSUE THREAD

**Issue by Hendrik2001** [klassentoernooi/klassentoernooi.github.io#10]
We moeten nieuws op de site kunnen zetten.

**Comment by Aimilius** [comment]
Kan je uitleggen wat je met blogfeed bedoelt?

**Comment by Hendrik2001** [comment]
volgensmij kan emiel nog steeds niets

**Comment by Aimilius** [comment]
Dit kan nu, er is alleen nog geen nieuws.
